[Auth] Signup
Nickoliz/tacktivity pull request #23
Opened 2020-09-02 17:37 UTC by Nickoliz

2020-09-02 19:05 UTC, ssoonmi requested changes

2020-09-02 19:05 UTC, ssoonmi commented on tacktivity/routes/util/auth.js
> +    return next();
you need to `return next()` on line 59 as well

2020-09-02 19:05 UTC, ssoonmi commented on tacktivity/routes/util/validation.js
> +    console.log(errors);
remove console.log's

2020-09-02 19:05 UTC, ssoonmi commented on tacktivity/db/models/user.js
> +          attributes: { exclude: ["firstName", "lastName", "updatedAt", "createdAt", "hashedPassword"] },
the current user is allowed to have information about all these fields that you added in the database

2020-09-02 19:36 UTC, Nickoliz commented on tacktivity/routes/util/auth.js
> +    return next();
Done.

2020-09-02 19:36 UTC, Nickoliz commented on tacktivity/routes/util/validation.js
> +    console.log(errors);
Done.

2020-09-02 19:41 UTC, Nickoliz commented on tacktivity/db/models/user.js
> +          attributes: { exclude: ["firstName", "lastName", "updatedAt", "createdAt", "hashedPassword"] },
Done. I thought this was causing error because I was getting a firstName requirement even though it was set to optional in my model and migration. I just tested and with "hashedPassword" on line 43 it's now working.

2020-09-03 17:37 UTC, ssoonmi requested changes

2020-09-03 17:37 UTC, ssoonmi commented on tacktivity/client/src/store/auth.js
> +}
the way the Redux store state changes for logging in, creating a user, and logging in a demo user is the exact same. So you only need one POJO action with one action type for dealing with all of them.

2020-09-03 17:37 UTC, ssoonmi commented on tacktivity/client/src/store/auth.js
>        dispatch(setUser(res.data.user));
no need to dispatch two actions that manipulate the store in the exact same way

2020-09-03 17:37 UTC, ssoonmi commented on tacktivity/routes/api/users.js
> -    .isLength({ min: 6, max: 70 }),
does this make sense why you don't need `hashedPassword` to be checked here?

2020-09-03 17:37 UTC, ssoonmi commented on tacktivity/client/src/store/auth.js
> +export const demoLogin = () => {
Demo login doesn't need to have its own thunk. You can use the login thunk!

2020-09-03 17:45 UTC, Nickoliz commented on tacktivity/routes/api/users.js
> -    .isLength({ min: 6, max: 70 }),
Yes. I think I changed that. This is checking the user entered password which definitely will not be exactly 60 characters. hashedPassword is used in the backend for auth. We don't validate a hashedPassword because the user never interacts with it.

2020-09-03 17:55 UTC, Nickoliz commented on tacktivity/client/src/store/auth.js
> +}
Got it. Makes total sense. I suppose I can dispatch the login() POJO with `null` for the age but is it okay if I keep the signup one to track things a bit?

2020-09-03 17:57 UTC, Nickoliz commented on tacktivity/client/src/store/auth.js
>        dispatch(setUser(res.data.user));
Makes total sense. DRYed this up by removing the CREATE_USER action creator and only using SET_USER now.

2020-09-03 18:08 UTC, ssoonmi commented on tacktivity/client/src/store/auth.js
> +}
you don't need the age to login right?

2020-09-03 18:38 UTC, Nickoliz commented on tacktivity/client/src/store/auth.js
> +export const demoLogin = () => {
Completed. Makes sense.

2020-09-03 18:57 UTC, ssoonmi requested changes
- [ ] should not be able to access the root page, `/`, if logged in. If logged in and trying to access the root page, redirect to `/home`

2020-09-03 19:22 UTC, ssoonmi approved these changes

2020-09-03 20:50 UTC, merged